# IND320 Dashboard

Denne notebooken dokumenterer utviklingen og analysen i IND320-prosjektet.

## Lenker

- [GitHub-repository](https://github.com/Kaja321/ind320-dashboard-kaja321)
- [Publisert Streamlit-app](https://ind320-dashboard-kaja321-2mtfc3yvzqjjw6wtcwjukq.streamlit.app/)

## Bruk av kunstig intelligens

Jeg har brukt kunstig intelligens som støtte under utviklingen av prosjektet. KI har blant annet blitt brukt til å forklare Git, GitHub, Streamlit og prosjektstruktur, samt til feilsøking og forslag til kode. Forslagene har blitt testet og vurdert før de ble tatt i bruk.

## Prosjektlogg

### Oppstart

Jeg opprettet først en egen prosjektmappe med en hovedfil for Streamlit, en requirements-fil og en gitignore-fil. Deretter opprettet jeg et offentlig repository på GitHub og koblet den lokale prosjektmappen til dette.

Jeg publiserte den første versjonen av appen på Streamlit Community Cloud. Etter dette opprettet jeg en struktur med fire sider: hovedside, tabellside, plottside og testside. Sidene ble testet lokalt før endringene ble lastet opp til GitHub.

## Dataanalyse

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("reservoirs.csv")
df.head()

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301

In [3]:
print("Antall rader og kolonner:", df.shape)

print("\nKolonnenavn:")
print(df.columns.tolist())

df.head()

Antall rader og kolonner: (14877, 11)

Kolonnenavn:
['dato_Id', 'omrType', 'omrnr', 'iso_aar', 'iso_uke', 'fyllingsgrad', 'kapasitet_TWh', 'fylling_TWh', 'neste_Publiseringsdato', 'fyllingsgrad_forrige_uke', 'endring_fyllingsgrad']

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301